
relative_links:
  enabled: true
  collections: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      title: "title"

theme: jekyll-theme-tactile